### ISSUE TITLE
Fixed URL and multiple sessions per day

### ISSUE THREAD

**Issue by david-a** [kquinsland/exist-duolingo-bridge#2]
Found these issues:

1. There is a fixed url (`https://duome.eu/kquinsland`) instead of taking the one from the config.
2. When there are multiple sessions per day, the script go through each and compare to the `min_xp` instead of summing per day.

**Comment by david-a** [comment]
resolving these issues: https://github.com/kquinsland/exist-duolingo-bridge/pull/1

**Comment by kquinsland** [comment]
Thanks.  Merged!
